import {useRouter} from "next/router";
import Head from "next/head";
import styled from "styled-components";
import Image from "next/image";
import {useApi} from "../../hooks/useApi";
import CubCoin from "../../components/CubCoin";
import ExperienceCoin from "../../components/ExperienceCoin";

const ProductDetail = () => {
  const router = useRouter();
  const {details} = router.query;
  const [task] = useApi(`/api/tasks/${details}`);

  return (
    <StyledLayout>
      <Head>
        <title>Task Details</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {task ? (
        <>
          <Image
            src={task.image}
            alt={"image of the detailed task"}
            width={175}
            height={122}
          ></Image>
          <p>
            Please do the following task:
            <br></br>
            <p className="taskUnderline">{task.title}</p>
          </p>
          <p>{`"${task.details}"`}</p>
          <p>
            Gold:
            <p className="goldIndicator">
              {" "}
              {task.gold} <CubCoin />
            </p>
          </p>
          <p>
            Experience:
            <p className="experienceIndicator">
              {" "}
              {task.experience} <ExperienceCoin />
            </p>
          </p>
        </>
      ) : (
        <p>Loading...</p>
      )}
    </StyledLayout>
  );
};

export default ProductDetail;

const StyledLayout = styled.div`
  width: 90vw;
  height: 70vh;
  text-align: center;
  font-size: 2rem;
  font-weight: bold;
  border: 4px solid white;
  border-radius: 25px;
  margin: auto;
  margin-top: 5vh;
  padding-top: 2rem;
  background: rgb(103, 17, 17);
  background: linear-gradient(
    120deg,
    rgba(103, 17, 17, 0.3) 0%,
    rgba(253, 29, 29, 0.3) 20%,
    rgba(255, 170, 50, 0.3) 100%
  );
  .taskUnderline {
    text-decoration: underline;
  }
  .goldIndicator {
    color: #e8871e;
    display: inline;
  }
  .experienceIndicator {
    color: #26c485;
    display: inline;
  }
`;
