import {useRouter} from "next/router";
import Head from "next/head";
import {useEffect, useState} from "react";

const ProductDetail = () => {
  const [task, setTask] = useState(null);
  const router = useRouter();
  const {taskId} = router.query;

  useEffect(() => {
    const getTask = async () => {
      try {
        const response = await fetch(`/api/tasks/${taskId}`);
        if (response.ok) {
          const data = await response.json();
          setTask(data);
        } else {
          throw new Error(`Fetch failed with status code ${response.status}`);
        }
      } catch (error) {
        alert(error);
      }
    };
    if (taskId) {
      getTask();
    }
  }, [taskId]);

  return (
    <>
      <Head>
        <title>Task Details</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {task ? (
        <>
          <p>Name: {task.title}</p>
          <p>For who?: {task.whichOne}</p>
          <p>Gold: {task.gold}</p>
          <p>Experience: {task.experience}</p>
        </>
      ) : (
        <p>Loading...</p>
      )}
    </>
  );
};

export default ProductDetail;
